### ISSUE TITLE
Declare event handlers directly on layout elements 

### ISSUE THREAD

**Issue by StokeMasterJack** [smyte/jsxstyle#45] opened 2016-11-03 16:08 UTC
It would be nice to do this:
`<Block  onClick={this.onRowClick}>Click Me</Block>`

instead of this:
`<Block  props={{onClick: this.onRowClick }}>Click Me</Block>`

**Comment by danielberndt** [comment] 2016-11-08 14:38
I guess this is a duplicate of https://github.com/smyte/jsxstyle/issues/32?

**Comment by meyer** [comment] 2016-11-10 00:41
@danielberndt yep!

**Closed by meyer** 2016-11-10 00:41 UTC
